# MACONLY OPTION DOWN

[env]
LC_CTYPE = "C-UTF-8"

[[keyboard.bindings]]
mods = "Alt"
key = "J"
chars = "\x1bj"

[[keyboard.bindings]]
key = "K"
mods = "Alt"
chars = "\x1bk"

# MAC ONLY OPTION ABOVE
#
#
#

[colors.primary]
background = "#242424"
foreground = "#ffffff"

[cursor]
style = "Beam"

[font]
size = 15

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.99

decorations_theme_variant = "Dark"

[window.padding]
x = 5
y = 0
